### ISSUE TITLE
战术包中的响应裁判指令出错 

### ISSUE THREAD

**Issue by Umbrella167** [Robocup-ssl-China/rocos#8]
裁判盒使用 FORCE START 和 其他脚本中使用 return  "exit" 报错
![Uploading 2024-04-25 14-14-57 的屏幕截图.png…]()

**Comment by Umbrella167** [comment]
11

**Comment by Umbrella167** [comment]
![bug](https://github.com/Robocup-ssl-China/rocos/assets/97947896/e2e6aab2-bd25-4cd3-a335-669f98cd2bff)

**Comment by Umbrella167** [comment]
![11](https://github.com/Robocup-ssl-China/rocos/assets/97947896/1b5e8e9d-1dd3-46ff-ad1c-4c280b969a47)

**Comment by Mark-tz** [comment]
刚提交了一下更新，在之前的代码逻辑里面没有对NormalPlay进行CUSTOM的判断，所以走的还是旧的逻辑，你的会报错应该是因为在Other.lua里面的gOppoConfig.NorPlay是一个不存在的Play，测试一下是否可行，我这边复现出来之后进行了修补，目前应该是已经可用了

**Comment by Umbrella167** [comment]
更新后bug已解决，感谢您的回复
